{
  "asyncapi": "3.0.0",
  "info": {
    "title": "p4pa-analytics-data-ingestion",
    "version": "0.0.1",
    "description": "AsyncAPI And Models",
    "x-generator": "springwolf"
  },
  "defaultContentType": "application/json",
  "servers": {
    "kafka-server": {
      "host": "localhost:9093",
      "protocol": "kafka"
    }
  },
  "channels": {
    "p4pa-payhub-audit-evh": {
      "address": "p4pa-payhub-audit-evh",
      "messages": {
        "string": {
          "$ref": "#/components/messages/string"
        }
      },
      "bindings": {
        "kafka": { }
      }
    },
    "p4pa-payhub-data-events-evh": {
      "address": "p4pa-payhub-data-events-evh",
      "messages": {
        "DataEventDTOObject": {
          "$ref": "#/components/messages/DataEventDTOObject"
        }
      },
      "bindings": {
        "kafka": { }
      }
    },
    "p4pa-payhub-payments-evh": {
      "address": "p4pa-payhub-payments-evh",
      "messages": {
        "PaymentEventDTOObject": {
          "$ref": "#/components/messages/PaymentEventDTOObject"
        }
      },
      "bindings": {
        "kafka": { }
      }
    }
  },
  "components": {
    "schemas": {
      "Action": {
        "title": "Action",
        "type": "string",
        "enum": [
          "I",
          "M",
          "A"
        ],
        "examples": [
          "\"I\""
        ]
      },
      "AssessmentDataEventDTO": {
        "type": "object",
        "examples": [
          {
            "eventDateTime": "2015-07-20T15:49:04-07:00",
            "eventDescription": "string",
            "eventId": "string",
            "eventType": "INGESTION",
            "payload": {
              "assessmentId": 0,
              "assessmentName": "string",
              "assessmentsDetailList": [
                {
                  "_links": {
                    "key": {
                      "deprecation": "string",
                      "href": "string",
                      "hreflang": "string",
                      "name": "string",
                      "profile": "string",
                      "templated": true,
                      "title": "string",
                      "type": "string"
                    }
                  },
                  "amountCents": 0,
                  "amountSubmitted": true,
                  "assessmentCode": "string",
                  "assessmentDescription": "string",
                  "assessmentDetailId": 0,
                  "assessmentId": 0,
                  "classificationLabel": "PAID",
                  "creationDate": "2015-07-20T15:49:04-07:00",
                  "dateReceipt": "2015-07-20T15:49:04-07:00",
                  "dateReporting": "2015-07-20T15:49:04-07:00",
                  "dateTreasury": "2015-07-20T15:49:04-07:00",
                  "debtPositionTypeOrgCode": "string",
                  "debtPositionTypeOrgId": 0,
                  "debtorFiscalCodeHash": "YmFzZTY0LWV4YW1wbGU=",
                  "iud": "string",
                  "iur": "string",
                  "iuv": "string",
                  "officeCode": "string",
                  "officeDescription": "string",
                  "organizationId": 0,
                  "paymentDateTime": "2015-07-20T15:49:04-07:00",
                  "receiptId": 0,
                  "sectionCode": "string",
                  "sectionDescription": "string",
                  "updateDate": "2015-07-20T15:49:04-07:00",
                  "updateOperatorExternalId": "string",
                  "updateTraceId": "string"
                }
              ],
              "debtPositionTypeOrgCode": "string",
              "flagManualGeneration": true,
              "iud": "string",
              "iur": "string",
              "iuv": "string",
              "operatorExternalUserId": "string",
              "organizationId": 0,
              "printed": true,
              "status": "CLOSED"
            },
            "traceId": "string"
          }
        ],
        "allOf": [
          {
            "$ref": "#/components/schemas/DataEventDTOObject"
          },
          {
            "type": "object",
            "properties": {
              "payload": {
                "$ref": "#/components/schemas/AssessmentEventDTO"
              }
            }
          }
        ]
      },
      "AssessmentEventDTO": {
        "title": "AssessmentEventDTO",
        "type": "object",
        "properties": {
          "assessmentId": {
            "type": "integer",
            "format": "int64"
          },
          "assessmentName": {
            "type": "string"
          },
          "assessmentsDetailList": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/AssessmentsDetail"
            }
          },
          "debtPositionTypeOrgCode": {
            "type": "string"
          },
          "flagManualGeneration": {
            "type": "boolean"
          },
          "iud": {
            "type": "string"
          },
          "iur": {
            "type": "string"
          },
          "iuv": {
            "type": "string"
          },
          "operatorExternalUserId": {
            "type": "string"
          },
          "organizationId": {
            "type": "integer",
            "format": "int64"
          },
          "printed": {
            "type": "boolean"
          },
          "status": {
            "$ref": "#/components/schemas/AssessmentStatus"
          }
        },
        "examples": [
          {
            "assessmentId": 0,
            "assessmentName": "string",
            "assessmentsDetailList": [
              {
                "_links": {
                  "key": {
                    "deprecation": "string",
                    "href": "string",
                    "hreflang": "string",
                    "name": "string",
                    "profile": "string",
                    "templated": true,
                    "title": "string",
                    "type": "string"
                  }
                },
                "amountCents": 0,
                "amountSubmitted": true,
                "assessmentCode": "string",
                "assessmentDescription": "string",
                "assessmentDetailId": 0,
                "assessmentId": 0,
                "classificationLabel": "PAID",
                "creationDate": "2015-07-20T15:49:04-07:00",
                "dateReceipt": "2015-07-20T15:49:04-07:00",
                "dateReporting": "2015-07-20T15:49:04-07:00",
                "dateTreasury": "2015-07-20T15:49:04-07:00",
                "debtPositionTypeOrgCode": "string",
                "debtPositionTypeOrgId": 0,
                "debtorFiscalCodeHash": "YmFzZTY0LWV4YW1wbGU=",
                "iud": "string",
                "iur": "string",
                "iuv": "string",
                "officeCode": "string",
                "officeDescription": "string",
                "organizationId": 0,
                "paymentDateTime": "2015-07-20T15:49:04-07:00",
                "receiptId": 0,
                "sectionCode": "string",
                "sectionDescription": "string",
                "updateDate": "2015-07-20T15:49:04-07:00",
                "updateOperatorExternalId": "string",
                "updateTraceId": "string"
              }
            ],
            "debtPositionTypeOrgCode": "string",
            "flagManualGeneration": true,
            "iud": "string",
            "iur": "string",
            "iuv": "string",
            "operatorExternalUserId": "string",
            "organizationId": 0,
            "printed": true,
            "status": "CLOSED"
          }
        ]
      },
      "AssessmentStatus": {
        "title": "AssessmentStatus",
        "type": "string",
        "enum": [
          "CLOSED",
          "CANCELLED",
          "ACTIVE"
        ],
        "examples": [
          "\"CLOSED\""
        ]
      },
      "AssessmentsDetail": {
        "title": "AssessmentsDetail",
        "type": "object",
        "properties": {
          "_links": {
            "type": "object",
            "additionalProperties": {
              "$ref": "#/components/schemas/Link"
            }
          },
          "amountCents": {
            "type": "integer",
            "format": "int64"
          },
          "amountSubmitted": {
            "type": "boolean"
          },
          "assessmentCode": {
            "type": "string"
          },
          "assessmentDescription": {
            "type": "string"
          },
          "assessmentDetailId": {
            "type": "integer",
            "format": "int64"
          },
          "assessmentId": {
            "type": "integer",
            "format": "int64"
          },
          "classificationLabel": {
            "$ref": "#/components/schemas/ClassificationLabel"
          },
          "creationDate": {
            "type": "string",
            "format": "date-time"
          },
          "dateReceipt": {
            "type": "string",
            "format": "date-time"
          },
          "dateReporting": {
            "type": "string",
            "format": "date-time"
          },
          "dateTreasury": {
            "type": "string",
            "format": "date-time"
          },
          "debtPositionTypeOrgCode": {
            "type": "string"
          },
          "debtPositionTypeOrgId": {
            "type": "integer",
            "format": "int64"
          },
          "debtorFiscalCodeHash": {
            "type": "string",
            "format": "byte"
          },
          "iud": {
            "type": "string"
          },
          "iur": {
            "type": "string"
          },
          "iuv": {
            "type": "string"
          },
          "officeCode": {
            "type": "string"
          },
          "officeDescription": {
            "type": "string"
          },
          "organizationId": {
            "type": "integer",
            "format": "int64"
          },
          "paymentDateTime": {
            "type": "string",
            "format": "date-time"
          },
          "receiptId": {
            "type": "integer",
            "format": "int64"
          },
          "sectionCode": {
            "type": "string"
          },
          "sectionDescription": {
            "type": "string"
          },
          "updateDate": {
            "type": "string",
            "format": "date-time"
          },
          "updateOperatorExternalId": {
            "type": "string"
          },
          "updateTraceId": {
            "type": "string"
          }
        },
        "examples": [
          {
            "_links": {
              "key": {
                "deprecation": "string",
                "href": "string",
                "hreflang": "string",
                "name": "string",
                "profile": "string",
                "templated": true,
                "title": "string",
                "type": "string"
              }
            },
            "amountCents": 0,
            "amountSubmitted": true,
            "assessmentCode": "string",
            "assessmentDescription": "string",
            "assessmentDetailId": 0,
            "assessmentId": 0,
            "classificationLabel": "PAID",
            "creationDate": "2015-07-20T15:49:04-07:00",
            "dateReceipt": "2015-07-20T15:49:04-07:00",
            "dateReporting": "2015-07-20T15:49:04-07:00",
            "dateTreasury": "2015-07-20T15:49:04-07:00",
            "debtPositionTypeOrgCode": "string",
            "debtPositionTypeOrgId": 0,
            "debtorFiscalCodeHash": "YmFzZTY0LWV4YW1wbGU=",
            "iud": "string",
            "iur": "string",
            "iuv": "string",
            "officeCode": "string",
            "officeDescription": "string",
            "organizationId": 0,
            "paymentDateTime": "2015-07-20T15:49:04-07:00",
            "receiptId": 0,
            "sectionCode": "string",
            "sectionDescription": "string",
            "updateDate": "2015-07-20T15:49:04-07:00",
            "updateOperatorExternalId": "string",
            "updateTraceId": "string"
          }
        ],
        "required": [
          "amountCents",
          "amountSubmitted",
          "assessmentId",
          "debtPositionTypeOrgCode",
          "debtPositionTypeOrgId",
          "debtorFiscalCodeHash",
          "iud",
          "iur",
          "iuv",
          "organizationId",
          "sectionCode"
        ]
      },
      "ClassificationLabel": {
        "title": "ClassificationLabel",
        "type": "string",
        "enum": [
          "PAID",
          "REPORTED",
          "CASHED"
        ],
        "examples": [
          "\"PAID\""
        ]
      },
      "DataEventDTOObject": {
        "discriminator": "eventType",
        "title": "DataEventDTO",
        "type": "object",
        "properties": {
          "eventDateTime": {
            "type": "string",
            "format": "date-time"
          },
          "eventDescription": {
            "type": "string"
          },
          "eventId": {
            "type": "string"
          },
          "eventType": {
            "$ref": "#/components/schemas/DataEventType"
          },
          "payload": {
            "type": "object"
          },
          "traceId": {
            "type": "string"
          }
        },
        "examples": [
          {
            "eventDateTime": "2015-07-20T15:49:04-07:00",
            "eventDescription": "string",
            "eventId": "string",
            "eventType": "INGESTION",
            "payload": { },
            "traceId": "string"
          }
        ]
      },
      "DataEventType": {
        "title": "DataEventType",
        "type": "string",
        "enum": [
          "INGESTION",
          "EXPORT_FILE",
          "ASSESSMENTS_CLASSIFICATION"
        ],
        "examples": [
          "\"INGESTION\""
        ]
      },
      "DebtPositionDTO": {
        "title": "DebtPositionDTO",
        "type": "object",
        "properties": {
          "creationDate": {
            "type": "string",
            "format": "date-time"
          },
          "debtPositionId": {
            "type": "integer",
            "format": "int64"
          },
          "debtPositionOrigin": {
            "$ref": "#/components/schemas/DebtPositionOrigin"
          },
          "debtPositionTypeOrgId": {
            "type": "integer",
            "format": "int64"
          },
          "description": {
            "type": "string"
          },
          "flagIuvVolatile": {
            "type": "boolean"
          },
          "flagPuPagoPaPayment": {
            "type": "boolean"
          },
          "iupdOrg": {
            "type": "string"
          },
          "multiDebtor": {
            "type": "boolean"
          },
          "organizationId": {
            "type": "integer",
            "format": "int64"
          },
          "paymentOptions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PaymentOptionDTO"
            }
          },
          "status": {
            "$ref": "#/components/schemas/DebtPositionStatus"
          },
          "updateDate": {
            "type": "string",
            "format": "date-time"
          },
          "updateOperatorExternalId": {
            "type": "string"
          },
          "updateTraceId": {
            "type": "string"
          },
          "validityDate": {
            "type": "string",
            "format": "date"
          }
        },
        "examples": [
          {
            "creationDate": "2015-07-20T15:49:04-07:00",
            "debtPositionId": 0,
            "debtPositionOrigin": "ORDINARY",
            "debtPositionTypeOrgId": 0,
            "description": "string",
            "flagIuvVolatile": true,
            "flagPuPagoPaPayment": true,
            "iupdOrg": "string",
            "multiDebtor": true,
            "organizationId": 0,
            "paymentOptions": [
              {
                "creationDate": "2015-07-20T15:49:04-07:00",
                "debtPositionId": 0,
                "description": "string",
                "installments": [
                  {
                    "amountCents": 0,
                    "balance": "string",
                    "creationDate": "2015-07-20T15:49:04-07:00",
                    "debtor": {
                      "address": "string",
                      "civic": "string",
                      "email": "string",
                      "entityType": "F",
                      "fiscalCode": "string",
                      "fullName": "string",
                      "location": "string",
                      "nation": "string",
                      "postalCode": "string",
                      "province": "string"
                    },
                    "dueDate": "2015-07-20",
                    "generateNotice": true,
                    "ingestionFlowFileAction": "\"I\"",
                    "ingestionFlowFileId": 0,
                    "ingestionFlowFileLineNumber": 0,
                    "installmentId": 0,
                    "iud": "string",
                    "iuf": "string",
                    "iun": "string",
                    "iupdPagopa": "string",
                    "iur": "string",
                    "iuv": "string",
                    "legacyPaymentMetadata": "string",
                    "nav": "string",
                    "notificationDate": "2015-07-20T15:49:04-07:00",
                    "notificationFeeCents": 0,
                    "paymentOptionId": 0,
                    "receiptId": 0,
                    "remittanceInformation": "string",
                    "sourceFlowName": "string",
                    "status": "TO_SYNC",
                    "switchToExpired": true,
                    "syncStatus": {
                      "syncError": "string",
                      "syncStatusFrom": "TO_SYNC",
                      "syncStatusTo": "TO_SYNC"
                    },
                    "transfers": [
                      {
                        "amountCents": 0,
                        "category": "string",
                        "creationDate": "2015-07-20T15:49:04-07:00",
                        "iban": "string",
                        "installmentId": 0,
                        "mbdAttachment": "string",
                        "orgFiscalCode": "string",
                        "orgName": "string",
                        "postalIban": "string",
                        "remittanceInformation": "string",
                        "stampHashDocument": "string",
                        "stampProvincialResidence": "string",
                        "stampType": "string",
                        "transferId": 0,
                        "transferIndex": 0,
                        "updateDate": "2015-07-20T15:49:04-07:00",
                        "updateOperatorExternalId": "string",
                        "updateTraceId": "string"
                      }
                    ],
                    "updateDate": "2015-07-20T15:49:04-07:00",
                    "updateOperatorExternalId": "string",
                    "updateTraceId": "string"
                  }
                ],
                "paymentOptionId": 0,
                "paymentOptionIndex": 0,
                "paymentOptionType": "SINGLE_INSTALLMENT",
                "status": "TO_SYNC",
                "totalAmountCents": 0,
                "updateDate": "2015-07-20T15:49:04-07:00",
                "updateOperatorExternalId": "string",
                "updateTraceId": "string"
              }
            ],
            "status": "TO_SYNC",
            "updateDate": "2015-07-20T15:49:04-07:00",
            "updateOperatorExternalId": "string",
            "updateTraceId": "string",
            "validityDate": "2015-07-20"
          }
        ],
        "required": [
          "debtPositionOrigin",
          "debtPositionTypeOrgId",
          "flagPuPagoPaPayment",
          "organizationId",
          "paymentOptions"
        ]
      },
      "DebtPositionEventDTO": {
        "type": "object",
        "examples": [
          {
            "eventDateTime": "2015-07-20T15:49:04-07:00",
            "eventDescription": "string",
            "eventId": "string",
            "eventType": "DP_CREATED",
            "payload": {
              "creationDate": "2015-07-20T15:49:04-07:00",
              "debtPositionId": 0,
              "debtPositionOrigin": "ORDINARY",
              "debtPositionTypeOrgId": 0,
              "description": "string",
              "flagIuvVolatile": true,
              "flagPuPagoPaPayment": true,
              "iupdOrg": "string",
              "multiDebtor": true,
              "organizationId": 0,
              "paymentOptions": [
                {
                  "creationDate": "2015-07-20T15:49:04-07:00",
                  "debtPositionId": 0,
                  "description": "string",
                  "installments": [
                    {
                      "amountCents": 0,
                      "balance": "string",
                      "creationDate": "2015-07-20T15:49:04-07:00",
                      "debtor": {
                        "address": "string",
                        "civic": "string",
                        "email": "string",
                        "entityType": "F",
                        "fiscalCode": "string",
                        "fullName": "string",
                        "location": "string",
                        "nation": "string",
                        "postalCode": "string",
                        "province": "string"
                      },
                      "dueDate": "2015-07-20",
                      "generateNotice": true,
                      "ingestionFlowFileAction": "\"I\"",
                      "ingestionFlowFileId": 0,
                      "ingestionFlowFileLineNumber": 0,
                      "installmentId": 0,
                      "iud": "string",
                      "iuf": "string",
                      "iun": "string",
                      "iupdPagopa": "string",
                      "iur": "string",
                      "iuv": "string",
                      "legacyPaymentMetadata": "string",
                      "nav": "string",
                      "notificationDate": "2015-07-20T15:49:04-07:00",
                      "notificationFeeCents": 0,
                      "paymentOptionId": 0,
                      "receiptId": 0,
                      "remittanceInformation": "string",
                      "sourceFlowName": "string",
                      "status": "TO_SYNC",
                      "switchToExpired": true,
                      "syncStatus": {
                        "syncError": "string",
                        "syncStatusFrom": "TO_SYNC",
                        "syncStatusTo": "TO_SYNC"
                      },
                      "transfers": [
                        {
                          "amountCents": 0,
                          "category": "string",
                          "creationDate": "2015-07-20T15:49:04-07:00",
                          "iban": "string",
                          "installmentId": 0,
                          "mbdAttachment": "string",
                          "orgFiscalCode": "string",
                          "orgName": "string",
                          "postalIban": "string",
                          "remittanceInformation": "string",
                          "stampHashDocument": "string",
                          "stampProvincialResidence": "string",
                          "stampType": "string",
                          "transferId": 0,
                          "transferIndex": 0,
                          "updateDate": "2015-07-20T15:49:04-07:00",
                          "updateOperatorExternalId": "string",
                          "updateTraceId": "string"
                        }
                      ],
                      "updateDate": "2015-07-20T15:49:04-07:00",
                      "updateOperatorExternalId": "string",
                      "updateTraceId": "string"
                    }
                  ],
                  "paymentOptionId": 0,
                  "paymentOptionIndex": 0,
                  "paymentOptionType": "SINGLE_INSTALLMENT",
                  "status": "TO_SYNC",
                  "totalAmountCents": 0,
                  "updateDate": "2015-07-20T15:49:04-07:00",
                  "updateOperatorExternalId": "string",
                  "updateTraceId": "string"
                }
              ],
              "status": "TO_SYNC",
              "updateDate": "2015-07-20T15:49:04-07:00",
              "updateOperatorExternalId": "string",
              "updateTraceId": "string",
              "validityDate": "2015-07-20"
            },
            "traceId": "string"
          }
        ],
        "allOf": [
          {
            "$ref": "#/components/schemas/PaymentEventDTOObject"
          },
          {
            "type": "object",
            "properties": {
              "payload": {
                "$ref": "#/components/schemas/DebtPositionDTO"
              }
            }
          }
        ]
      },
      "DebtPositionOrigin": {
        "title": "DebtPositionOrigin",
        "type": "string",
        "enum": [
          "ORDINARY",
          "ORDINARY_SIL",
          "SPONTANEOUS",
          "SPONTANEOUS_SIL",
          "SPONTANEOUS_MIXED",
          "SECONDARY_ORG",
          "RECEIPT_FILE",
          "RECEIPT_PAGOPA",
          "REPORTING_PAGOPA"
        ],
        "examples": [
          "\"ORDINARY\""
        ]
      },
      "DebtPositionStatus": {
        "title": "DebtPositionStatus",
        "type": "string",
        "enum": [
          "TO_SYNC",
          "REPORTED",
          "PAID",
          "PARTIALLY_PAID",
          "CANCELLED",
          "EXPIRED",
          "UNPAID",
          "DRAFT"
        ],
        "examples": [
          "\"TO_SYNC\""
        ]
      },
      "ExportDataDTO": {
        "title": "ExportDataDTO",
        "type": "object",
        "properties": {
          "exportDate": {
            "type": "string",
            "format": "date"
          },
          "exportFileId": {
            "type": "integer",
            "format": "int64"
          },
          "exportFileType": {
            "$ref": "#/components/schemas/ExportFileTypeEnum"
          },
          "exportedRows": {
            "type": "integer",
            "format": "int64"
          },
          "fileSize": {
            "type": "integer",
            "format": "int64"
          },
          "organizationId": {
            "type": "integer",
            "format": "int64"
          }
        },
        "examples": [
          {
            "exportDate": "2015-07-20",
            "exportFileId": 0,
            "exportFileType": "PAID",
            "exportedRows": 0,
            "fileSize": 0,
            "organizationId": 0
          }
        ]
      },
      "ExportDataEventDTO": {
        "type": "object",
        "examples": [
          {
            "eventDateTime": "2015-07-20T15:49:04-07:00",
            "eventDescription": "string",
            "eventId": "string",
            "eventType": "\"INGESTION\"",
            "payload": {
              "exportDate": "2015-07-20",
              "exportFileId": 0,
              "exportFileType": "PAID",
              "exportedRows": 0,
              "fileSize": 0,
              "organizationId": 0
            },
            "traceId": "string"
          }
        ],
        "allOf": [
          {
            "$ref": "#/components/schemas/DataEventDTOObject"
          },
          {
            "type": "object",
            "properties": {
              "payload": {
                "$ref": "#/components/schemas/ExportDataDTO"
              }
            }
          }
        ]
      },
      "ExportFileTypeEnum": {
        "title": "ExportFileTypeEnum",
        "type": "string",
        "enum": [
          "PAID",
          "CLASSIFICATIONS",
          "PAYMENTS_REPORTING",
          "RECEIPTS_ARCHIVING"
        ],
        "examples": [
          "\"PAID\""
        ]
      },
      "HeadersNotDocumented": {
        "title": "HeadersNotDocumented",
        "type": "object",
        "properties": { },
        "description": "There can be headers, but they are not explicitly documented.",
        "examples": [
          { }
        ]
      },
      "IngestionDataDTO": {
        "title": "IngestionDataDTO",
        "type": "object",
        "properties": {
          "ingestionFlowFileId": {
            "type": "integer",
            "format": "int64"
          },
          "organizationId": {
            "type": "integer",
            "format": "int64"
          },
          "processedRows": {
            "type": "integer",
            "format": "int64"
          },
          "status": {
            "$ref": "#/components/schemas/IngestionFlowFileStatus"
          },
          "totalRows": {
            "type": "integer",
            "format": "int64"
          }
        },
        "examples": [
          {
            "ingestionFlowFileId": 0,
            "organizationId": 0,
            "processedRows": 0,
            "status": "UPLOADED",
            "totalRows": 0
          }
        ]
      },
      "IngestionDataEventDTO": {
        "type": "object",
        "examples": [
          {
            "eventDateTime": "2015-07-20T15:49:04-07:00",
            "eventDescription": "string",
            "eventId": "string",
            "eventType": "\"INGESTION\"",
            "payload": {
              "ingestionFlowFileId": 0,
              "organizationId": 0,
              "processedRows": 0,
              "status": "UPLOADED",
              "totalRows": 0
            },
            "traceId": "string"
          }
        ],
        "allOf": [
          {
            "$ref": "#/components/schemas/DataEventDTOObject"
          },
          {
            "type": "object",
            "properties": {
              "payload": {
                "$ref": "#/components/schemas/IngestionDataDTO"
              }
            }
          }
        ]
      },
      "IngestionFlowFileStatus": {
        "title": "IngestionFlowFileStatus",
        "type": "string",
        "enum": [
          "UPLOADED",
          "PROCESSING",
          "COMPLETED",
          "ERROR",
          "WAITING_FILE",
          "WARNING"
        ],
        "examples": [
          "\"UPLOADED\""
        ]
      },
      "InstallmentDTO": {
        "title": "InstallmentDTO",
        "type": "object",
        "properties": {
          "amountCents": {
            "type": "integer",
            "format": "int64"
          },
          "balance": {
            "type": "string"
          },
          "creationDate": {
            "type": "string",
            "format": "date-time"
          },
          "debtor": {
            "$ref": "#/components/schemas/PersonDTO"
          },
          "dueDate": {
            "type": "string",
            "format": "date"
          },
          "generateNotice": {
            "type": "boolean"
          },
          "ingestionFlowFileAction": {
            "$ref": "#/components/schemas/Action"
          },
          "ingestionFlowFileId": {
            "type": "integer",
            "format": "int64"
          },
          "ingestionFlowFileLineNumber": {
            "type": "integer",
            "format": "int64"
          },
          "installmentId": {
            "type": "integer",
            "format": "int64"
          },
          "iud": {
            "type": "string"
          },
          "iuf": {
            "type": "string"
          },
          "iun": {
            "type": "string"
          },
          "iupdPagopa": {
            "type": "string"
          },
          "iur": {
            "type": "string"
          },
          "iuv": {
            "type": "string"
          },
          "legacyPaymentMetadata": {
            "type": "string"
          },
          "nav": {
            "type": "string"
          },
          "notificationDate": {
            "type": "string",
            "format": "date-time"
          },
          "notificationFeeCents": {
            "type": "integer",
            "format": "int64"
          },
          "paymentOptionId": {
            "type": "integer",
            "format": "int64"
          },
          "receiptId": {
            "type": "integer",
            "format": "int64"
          },
          "remittanceInformation": {
            "type": "string"
          },
          "sourceFlowName": {
            "type": "string"
          },
          "status": {
            "$ref": "#/components/schemas/InstallmentStatus"
          },
          "switchToExpired": {
            "type": "boolean"
          },
          "syncStatus": {
            "$ref": "#/components/schemas/InstallmentSyncStatus"
          },
          "transfers": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/TransferDTO"
            }
          },
          "updateDate": {
            "type": "string",
            "format": "date-time"
          },
          "updateOperatorExternalId": {
            "type": "string"
          },
          "updateTraceId": {
            "type": "string"
          }
        },
        "examples": [
          {
            "amountCents": 0,
            "balance": "string",
            "creationDate": "2015-07-20T15:49:04-07:00",
            "debtor": {
              "address": "string",
              "civic": "string",
              "email": "string",
              "entityType": "F",
              "fiscalCode": "string",
              "fullName": "string",
              "location": "string",
              "nation": "string",
              "postalCode": "string",
              "province": "string"
            },
            "dueDate": "2015-07-20",
            "generateNotice": true,
            "ingestionFlowFileAction": "\"I\"",
            "ingestionFlowFileId": 0,
            "ingestionFlowFileLineNumber": 0,
            "installmentId": 0,
            "iud": "string",
            "iuf": "string",
            "iun": "string",
            "iupdPagopa": "string",
            "iur": "string",
            "iuv": "string",
            "legacyPaymentMetadata": "string",
            "nav": "string",
            "notificationDate": "2015-07-20T15:49:04-07:00",
            "notificationFeeCents": 0,
            "paymentOptionId": 0,
            "receiptId": 0,
            "remittanceInformation": "string",
            "sourceFlowName": "string",
            "status": "TO_SYNC",
            "switchToExpired": true,
            "syncStatus": {
              "syncError": "string",
              "syncStatusFrom": "TO_SYNC",
              "syncStatusTo": "TO_SYNC"
            },
            "transfers": [
              {
                "amountCents": 0,
                "category": "string",
                "creationDate": "2015-07-20T15:49:04-07:00",
                "iban": "string",
                "installmentId": 0,
                "mbdAttachment": "string",
                "orgFiscalCode": "string",
                "orgName": "string",
                "postalIban": "string",
                "remittanceInformation": "string",
                "stampHashDocument": "string",
                "stampProvincialResidence": "string",
                "stampType": "string",
                "transferId": 0,
                "transferIndex": 0,
                "updateDate": "2015-07-20T15:49:04-07:00",
                "updateOperatorExternalId": "string",
                "updateTraceId": "string"
              }
            ],
            "updateDate": "2015-07-20T15:49:04-07:00",
            "updateOperatorExternalId": "string",
            "updateTraceId": "string"
          }
        ],
        "required": [
          "amountCents",
          "debtor",
          "remittanceInformation"
        ]
      },
      "InstallmentStatus": {
        "title": "InstallmentStatus",
        "type": "string",
        "enum": [
          "TO_SYNC",
          "REPORTED",
          "PAID",
          "CANCELLED",
          "INVALID",
          "EXPIRED",
          "UNPAID",
          "UNPAYABLE",
          "DRAFT"
        ],
        "examples": [
          "\"TO_SYNC\""
        ]
      },
      "InstallmentSyncStatus": {
        "title": "InstallmentSyncStatus",
        "type": "object",
        "properties": {
          "syncError": {
            "type": "string"
          },
          "syncStatusFrom": {
            "$ref": "#/components/schemas/InstallmentStatus"
          },
          "syncStatusTo": {
            "$ref": "#/components/schemas/InstallmentStatus"
          }
        },
        "examples": [
          {
            "syncError": "string",
            "syncStatusFrom": "\"TO_SYNC\"",
            "syncStatusTo": "\"TO_SYNC\""
          }
        ],
        "required": [
          "syncStatusFrom",
          "syncStatusTo"
        ]
      },
      "Link": {
        "title": "Link",
        "type": "object",
        "properties": {
          "deprecation": {
            "type": "string"
          },
          "href": {
            "type": "string"
          },
          "hreflang": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "profile": {
            "type": "string"
          },
          "templated": {
            "type": "boolean"
          },
          "title": {
            "type": "string"
          },
          "type": {
            "type": "string"
          }
        },
        "examples": [
          {
            "deprecation": "string",
            "href": "string",
            "hreflang": "string",
            "name": "string",
            "profile": "string",
            "templated": true,
            "title": "string",
            "type": "string"
          }
        ]
      },
      "PaymentEventDTOObject": {
        "discriminator": "eventType",
        "title": "PaymentEventDTO",
        "type": "object",
        "properties": {
          "eventDateTime": {
            "type": "string",
            "format": "date-time"
          },
          "eventDescription": {
            "type": "string"
          },
          "eventId": {
            "type": "string"
          },
          "eventType": {
            "$ref": "#/components/schemas/PaymentEventType"
          },
          "payload": {
            "type": "object"
          },
          "traceId": {
            "type": "string"
          }
        },
        "examples": [
          {
            "eventDateTime": "2015-07-20T15:49:04-07:00",
            "eventDescription": "string",
            "eventId": "string",
            "eventType": "DP_CREATED",
            "payload": { },
            "traceId": "string"
          }
        ]
      },
      "PaymentEventType": {
        "title": "PaymentEventType",
        "type": "string",
        "enum": [
          "DP_CREATED",
          "DP_UPDATED",
          "DP_CANCELLED",
          "DPI_ADDED",
          "DPI_UPDATED",
          "DPI_CANCELLED",
          "DPI_EXPIRED",
          "DPI_REPORTED",
          "RT_RECEIVED",
          "SYNC_ERROR",
          "IO_NOTIFIED",
          "SEND_NOTIFICATION_CREATED",
          "SEND_NOTIFICATION_ERROR",
          "SEND_NOTIFICATION_DATE"
        ],
        "examples": [
          "\"DP_CREATED\""
        ]
      },
      "PaymentOptionDTO": {
        "title": "PaymentOptionDTO",
        "type": "object",
        "properties": {
          "creationDate": {
            "type": "string",
            "format": "date-time"
          },
          "debtPositionId": {
            "type": "integer",
            "format": "int64"
          },
          "description": {
            "type": "string"
          },
          "installments": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/InstallmentDTO"
            }
          },
          "paymentOptionId": {
            "type": "integer",
            "format": "int64"
          },
          "paymentOptionIndex": {
            "type": "integer",
            "format": "int32"
          },
          "paymentOptionType": {
            "$ref": "#/components/schemas/PaymentOptionTypeEnum"
          },
          "status": {
            "$ref": "#/components/schemas/PaymentOptionStatus"
          },
          "totalAmountCents": {
            "type": "integer",
            "format": "int64"
          },
          "updateDate": {
            "type": "string",
            "format": "date-time"
          },
          "updateOperatorExternalId": {
            "type": "string"
          },
          "updateTraceId": {
            "type": "string"
          }
        },
        "examples": [
          {
            "creationDate": "2015-07-20T15:49:04-07:00",
            "debtPositionId": 0,
            "description": "string",
            "installments": [
              {
                "amountCents": 0,
                "balance": "string",
                "creationDate": "2015-07-20T15:49:04-07:00",
                "debtor": {
                  "address": "string",
                  "civic": "string",
                  "email": "string",
                  "entityType": "F",
                  "fiscalCode": "string",
                  "fullName": "string",
                  "location": "string",
                  "nation": "string",
                  "postalCode": "string",
                  "province": "string"
                },
                "dueDate": "2015-07-20",
                "generateNotice": true,
                "ingestionFlowFileAction": "\"I\"",
                "ingestionFlowFileId": 0,
                "ingestionFlowFileLineNumber": 0,
                "installmentId": 0,
                "iud": "string",
                "iuf": "string",
                "iun": "string",
                "iupdPagopa": "string",
                "iur": "string",
                "iuv": "string",
                "legacyPaymentMetadata": "string",
                "nav": "string",
                "notificationDate": "2015-07-20T15:49:04-07:00",
                "notificationFeeCents": 0,
                "paymentOptionId": 0,
                "receiptId": 0,
                "remittanceInformation": "string",
                "sourceFlowName": "string",
                "status": "TO_SYNC",
                "switchToExpired": true,
                "syncStatus": {
                  "syncError": "string",
                  "syncStatusFrom": "TO_SYNC",
                  "syncStatusTo": "TO_SYNC"
                },
                "transfers": [
                  {
                    "amountCents": 0,
                    "category": "string",
                    "creationDate": "2015-07-20T15:49:04-07:00",
                    "iban": "string",
                    "installmentId": 0,
                    "mbdAttachment": "string",
                    "orgFiscalCode": "string",
                    "orgName": "string",
                    "postalIban": "string",
                    "remittanceInformation": "string",
                    "stampHashDocument": "string",
                    "stampProvincialResidence": "string",
                    "stampType": "string",
                    "transferId": 0,
                    "transferIndex": 0,
                    "updateDate": "2015-07-20T15:49:04-07:00",
                    "updateOperatorExternalId": "string",
                    "updateTraceId": "string"
                  }
                ],
                "updateDate": "2015-07-20T15:49:04-07:00",
                "updateOperatorExternalId": "string",
                "updateTraceId": "string"
              }
            ],
            "paymentOptionId": 0,
            "paymentOptionIndex": 0,
            "paymentOptionType": "SINGLE_INSTALLMENT",
            "status": "TO_SYNC",
            "totalAmountCents": 0,
            "updateDate": "2015-07-20T15:49:04-07:00",
            "updateOperatorExternalId": "string",
            "updateTraceId": "string"
          }
        ],
        "required": [
          "installments",
          "paymentOptionType",
          "totalAmountCents"
        ]
      },
      "PaymentOptionStatus": {
        "title": "PaymentOptionStatus",
        "type": "string",
        "enum": [
          "TO_SYNC",
          "REPORTED",
          "PAID",
          "PARTIALLY_PAID",
          "CANCELLED",
          "INVALID",
          "EXPIRED",
          "UNPAID",
          "UNPAYABLE",
          "DRAFT"
        ],
        "examples": [
          "\"TO_SYNC\""
        ]
      },
      "PaymentOptionTypeEnum": {
        "title": "PaymentOptionTypeEnum",
        "type": "string",
        "enum": [
          "SINGLE_INSTALLMENT",
          "REDUCED_SINGLE_INSTALLMENT",
          "INSTALLMENTS",
          "DOWN_PAYMENT"
        ],
        "examples": [
          "\"SINGLE_INSTALLMENT\""
        ]
      },
      "PersonDTO": {
        "title": "PersonDTO",
        "type": "object",
        "properties": {
          "address": {
            "type": "string"
          },
          "civic": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "entityType": {
            "$ref": "#/components/schemas/PersonEntityType"
          },
          "fiscalCode": {
            "type": "string"
          },
          "fullName": {
            "type": "string"
          },
          "location": {
            "type": "string"
          },
          "nation": {
            "type": "string"
          },
          "postalCode": {
            "type": "string"
          },
          "province": {
            "type": "string"
          }
        },
        "examples": [
          {
            "address": "string",
            "civic": "string",
            "email": "string",
            "entityType": "F",
            "fiscalCode": "string",
            "fullName": "string",
            "location": "string",
            "nation": "string",
            "postalCode": "string",
            "province": "string"
          }
        ],
        "required": [
          "entityType",
          "fiscalCode",
          "fullName"
        ]
      },
      "PersonEntityType": {
        "title": "PersonEntityType",
        "type": "string",
        "enum": [
          "F",
          "G"
        ],
        "examples": [
          "\"F\""
        ]
      },
      "TransferDTO": {
        "title": "TransferDTO",
        "type": "object",
        "properties": {
          "amountCents": {
            "type": "integer",
            "format": "int64"
          },
          "category": {
            "type": "string"
          },
          "creationDate": {
            "type": "string",
            "format": "date-time"
          },
          "iban": {
            "type": "string"
          },
          "installmentId": {
            "type": "integer",
            "format": "int64"
          },
          "mbdAttachment": {
            "type": "string"
          },
          "orgFiscalCode": {
            "type": "string"
          },
          "orgName": {
            "type": "string"
          },
          "postalIban": {
            "type": "string"
          },
          "remittanceInformation": {
            "type": "string"
          },
          "stampHashDocument": {
            "type": "string"
          },
          "stampProvincialResidence": {
            "type": "string"
          },
          "stampType": {
            "type": "string"
          },
          "transferId": {
            "type": "integer",
            "format": "int64"
          },
          "transferIndex": {
            "type": "integer",
            "format": "int32"
          },
          "updateDate": {
            "type": "string",
            "format": "date-time"
          },
          "updateOperatorExternalId": {
            "type": "string"
          },
          "updateTraceId": {
            "type": "string"
          }
        },
        "examples": [
          {
            "amountCents": 0,
            "category": "string",
            "creationDate": "2015-07-20T15:49:04-07:00",
            "iban": "string",
            "installmentId": 0,
            "mbdAttachment": "string",
            "orgFiscalCode": "string",
            "orgName": "string",
            "postalIban": "string",
            "remittanceInformation": "string",
            "stampHashDocument": "string",
            "stampProvincialResidence": "string",
            "stampType": "string",
            "transferId": 0,
            "transferIndex": 0,
            "updateDate": "2015-07-20T15:49:04-07:00",
            "updateOperatorExternalId": "string",
            "updateTraceId": "string"
          }
        ],
        "required": [
          "amountCents",
          "category",
          "orgFiscalCode",
          "orgName",
          "remittanceInformation",
          "transferIndex"
        ]
      },
      "string": {
        "type": "string",
        "examples": [
          "\"string\""
        ]
      }
    },
    "messages": {
      "DataEventDTOObject": {
        "headers": {
          "$ref": "#/components/schemas/HeadersNotDocumented"
        },
        "payload": {
          "schemaFormat": "application/vnd.aai.asyncapi+json;version=3.0.0",
          "schema": {
            "oneOf": [
              {
                "$ref": "#/components/schemas/DataEventDTOObject"
              },
              {
                "$ref": "#/components/schemas/AssessmentDataEventDTO"
              },
              {
                "$ref": "#/components/schemas/ExportDataEventDTO"
              },
              {
                "$ref": "#/components/schemas/IngestionDataEventDTO"
              }
            ]
          }
        },
        "name": "DataEventDTOObject",
        "title": "DataEventDTOObject",
        "bindings": {
          "kafka": { }
        }
      },
      "PaymentEventDTOObject": {
        "headers": {
          "$ref": "#/components/schemas/HeadersNotDocumented"
        },
        "payload": {
          "schemaFormat": "application/vnd.aai.asyncapi+json;version=3.0.0",
          "schema": {
            "oneOf": [
              {
                "$ref": "#/components/schemas/PaymentEventDTOObject"
              },
              {
                "$ref": "#/components/schemas/DebtPositionEventDTO"
              }
            ]
          }
        },
        "name": "PaymentEventDTOObject",
        "title": "PaymentEventDTOObject",
        "bindings": {
          "kafka": { }
        }
      },
      "string": {
        "headers": {
          "$ref": "#/components/schemas/HeadersNotDocumented"
        },
        "payload": {
          "schemaFormat": "application/vnd.aai.asyncapi+json;version=3.0.0",
          "schema": {
            "type": "string",
            "examples": [
              "\"string\""
            ]
          }
        },
        "name": "string",
        "title": "string",
        "bindings": {
          "kafka": { }
        }
      }
    }
  },
  "operations": {
    "p4pa-payhub-audit-evh_receive_AuditConsumer": {
      "action": "receive",
      "channel": {
        "$ref": "#/channels/p4pa-payhub-audit-evh"
      },
      "description": "Auto-generated description",
      "bindings": {
        "kafka": { }
      },
      "messages": [
        {
          "$ref": "#/channels/p4pa-payhub-audit-evh/messages/string"
        }
      ]
    },
    "p4pa-payhub-data-events-evh_receive_DataEventsConsumer": {
      "action": "receive",
      "channel": {
        "$ref": "#/channels/p4pa-payhub-data-events-evh"
      },
      "description": "Auto-generated description",
      "bindings": {
        "kafka": { }
      },
      "messages": [
        {
          "$ref": "#/channels/p4pa-payhub-data-events-evh/messages/DataEventDTOObject"
        }
      ]
    },
    "p4pa-payhub-payments-evh_receive_PaymentsConsumer": {
      "action": "receive",
      "channel": {
        "$ref": "#/channels/p4pa-payhub-payments-evh"
      },
      "description": "Auto-generated description",
      "bindings": {
        "kafka": { }
      },
      "messages": [
        {
          "$ref": "#/channels/p4pa-payhub-payments-evh/messages/PaymentEventDTOObject"
        }
      ]
    }
  }
}